### PR TITLE
RPE-1026 Fully working UMI setup

### PR DESCRIPTION
**Pull request by timja**
### JIRA link (if applicable) ###
https://tools.hmcts.net/jira/browse/RPE-1026

### Change description ###
Converts previous azure-cli attempt to use [pulumi](https://pulumi.io/quickstart/azure/index.html)
Its basically a wrapper around terraform that lets you programmatically create resources in a type safe way.

Very easy to use, and great for config as code implementation based on a config file

The previous terraform attempt to do something like this was horrific and it was impossible to make it work in a cross subscription way, it is trivial with pulumi

This builds on the work that converted the terraform to azure-cli and supersedes it:
https://github.com/hmcts/azure-managed-identity-config/pull/4

**Does this PR introduce a breaking change?** (check one with "x")

```
[ ] Yes
[ ] No
```

### CODE REVIEW

**Review by timwebster9 — COMMENTED** [review]
When you say 'wrapper around Terraform' do you mean Pulumi implicitly uses TF libraries?

Also, how does the remote state stuff work?

Did it work across subscriptions?

**Comment by timja** [comment]
Yes they've written a tool that generates bindings based on the terraform resources
Same as terraform but need to manage upload and download of the state until this PR is merged https://github.com/pulumi/pulumi/pull/2455

Yes worked across subscriptions fine

**Comment by timwebster9** [comment]
> Yes they've written a tool that generates bindings based on the terraform resources
> Same as terraform but need to manage upload and download of the state until this PR is merged [pulumi/pulumi#2455](https://github.com/pulumi/pulumi/pull/2455)
> 
> Yes worked across subscriptions fine

OK so is it just a matter of 'not bothering' with remote state for the moment?  What do you recommend?

**Comment by timja** [comment]
Just manually upload / download it in azure devops, shouldn't be much work.
It won't work without remote state as it detects they exist but requires them to be imported

**Review by timwebster9 — APPROVED** [review]

**Pull request merged**
